# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'activerecord', require: 'active_record'
gem 'rake'
gem 'sinatra'
gem 'sinatra-activerecord', require: 'sinatra/activerecord'
gem 'sqlite3'

group :test, :develop do
  gem 'pry-byebug'
  gem 'rubocop'
end
